# Generated by Django 2.2 on 2020-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_yearofstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='YearofStudy',
            field=models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year'), ('M1st', 'M.Tech First Year'), ('M2nd', 'M.Tech Second Year'), ('phd', 'PHD')], default='First Year', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Other', max_length=10, null=True),
        ),
    ]
