# Generated by Django 2.2 on 2020-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Dept',
            field=models.CharField(choices=[('cse', 'CSE'), ('ee', 'EE'), ('ece', 'ECE'), ('me', 'ME'), ('mme', 'MME'), ('ce', 'CE')], default='CSE', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='RegNo',
            field=models.CharField(default='12u10888', max_length=9),
        ),
    ]
